Refactor_SW/SW/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/logs', 'WebServer.views.View_ServerLogs'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('User.urls', namespace="user")),
    url(r'^$', 'User.views.home', name="home"),
    #    url(r'^$', 'WebServer.views.home', name="home"),
]

Refactor_SW/WebServer/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from WebServer.views import userinterface, register, error, list_all, list_id, list_off, list_on, list_ar, \
    list_vr, test_interface, launch_mod, view_login, view_logout

app_name = 'WebServer'

urlpatterns = [
    url(r'^login/', view_login, name='login'),
    url(r'^logout/', view_logout, name='logout'),
    url(r'^register/', register, name='register'),
    url(r'^index/', userinterface, name='userinterface'),
    url(r'^error/', error, name='error'),
    url(r'^list_all/', list_all, name='list_all'),
    url(r'^list_vr/', list_vr, name='list_vr'),
    url(r'^list_ar/', list_ar, name='list_ar'),
    url(r'^list_on/', list_on, name='list_on'),
    url(r'^list_off/', list_off, name='list_off'),
    url(r'^list_id/', list_id, name='list_id'),
    url(r'^launch_mod', launch_mod, name='launch_mod'),
    url(r'^test_interface', test_interface, name='test_interface')
]

Refactor_SW/templates/cannotaccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Login</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <a class="navbar-brand" href="login.html">MRinside</a>
    </div>
</nav>
<div class="col-md-4"></div>
<div class="col-md-4">
    <h2>401 Authorized</h2>
</div>

Refactor_SW/templates/devinterface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Dev Interface</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">MRinside</a>
    </div>
</nav>
<div class="col-md-4"></div>
<div class="col-md-4">
    <h2>401 Authorized</h2>
</div>

Refactor_SW/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>ERREUR</h1>
</body>
</html>

Refactor_SW/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Welcome</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">MRinside</a>
        </div>
    </nav>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <h1>MRinside</h1>
        <h2>Why content yourself with only one reality?</h2>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <a class="btn-default" href="/user/login/">Login</a>
        <a class="btn-default" href="/user/register/">Register</a>
    </div>
</body>

Refactor_SW/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Login</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">MRinside</a>
    </div>
</nav>
<div class="col-md-4"></div>
<div class="col-md-4">
<form class="form-group" method="post">
            {% csrf_token %}
    <div class="form-group">
        <label for="Username">Username</label>
        <input type="text" class="form-control" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="InputPassword">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <button class="btn-primary" type="submit">Login</button>
    </div>
</form>
<div>
</br>
    <p>Not already registered? Create an account!</p>
    <a class="btn btn-primary" href="/user/register">Register</a>
</div>
</div>
<div class="col-md-4"></div>
</body>
</html>

Refactor_SW/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
<h1>You are logged out :(</h1>
</body>
</html>

Refactor_SW/templates/moduledevpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Refactor_SW/templates/modulepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Dev Interface</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">MRinside</a>
    </div>
    {% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <a href="/user/logout/" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-log-out" id="logIcon"></span>
                    </a>
                </li>
            </ul>
         </ul>
        {% endif %}
    </ul>
</nav>
<div class="col-md-4"></div>

Refactor_SW/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MRinside - Register</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">MRinside</a>
        </div>
    </nav>
    <div class="col-md-4"></div>
    <div class="col-md-4">
    <form id="form" action="/user/register/" method="post" id="register" autocomplete="off">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
        </div>
        <div class="fieldWrapper">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
        </div>
        <div class="fieldWrapper">
            {{ form.username.errors }}
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="fieldWrapper">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="fieldWrapper">
            {{ form.password1.label_tag }}
            {{ form.password1 }}
        </div>
        <div class="fieldWrapper">
            {{ form.password2.label_tag }}
            {{ form.password2 }}
        </div>
        <input type="submit" value="Register"/>
    </form>
    </div>
</body>
</html>

Refactor_SW/templates/userinterface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MRinside - Index</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">MRinside</a>
        </div>
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="/user/logout/">
                        {% csrf_token %}
                        <span class="glyphicon glyphicon-log-out" id="logIcon"></span>
                    </a>
                </li>
              </ul>
            </ul>
            {% endif %}
    </nav>
    <div class="col-md-4">
    <form class="form-group">
        <div class="form-group">
            <label for="List_vr">Lister tous les modules VR.</label>
             <form action="{% url 'user:list_vr' %}" method="post">
                 {% csrf_token %}
                <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <div class="form-group">
            <label for="List_all">Lister tous les modules.</label>
             <form action="{% url 'user:list_all' %}" method="post">
                 {% csrf_token %}
                <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <div class="form-group">
            <label for="List_ar">Lister tous les modules AR.</label>
             <form action="{% url 'user:list_ar' %}" method="post">
                 {% csrf_token %}
                <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <div class="form-group">
            <label for="List_off">Lister tous les modules offline.</label>
             <form action="{% url 'user:list_off' %}" method="post">
                 {% csrf_token %}
                <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <div class="form-group">
            <label for="List_on">Lister tous les modules online.</label>
             <form action="{% url 'user:list_on' %}" method="post">
                 {% csrf_token %}
                <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <div class="form-group">
            <label for="List_id">Lister tous les modules ID.</label>
             <form action="{% url 'user:list_id' %}" method="post">
                 {% csrf_token %}
                 <input type="text" class="form-control" id="module_id" placeholder="Module ID">
                 <input class="btn btn-default" type="submit" value="Lister">
             </form>
        </div>
        <!--
        <div class="form-group">
            <label for="Launch_module">Lancer le module ID.</label>
             <form action="{% url 'user:launch_mod' %}" method="post">
                 {% csrf_token %}
                 <input type="text" class="form-control" id="module_id" placeholder="Module ID">
                 <input class="btn btn-default" type="submit" value="Lancer">
             </form>
        </div>-->
    </form>
    </div>
</body>
</html>